### ISSUE TITLE
receiveStreams is ambiguous

### ISSUE THREAD

**Issue by kixelated** [w3c/web-transport#132]
Quick quiz: does `receiveStreams` return bidirectional streams, unidirectional streams, or both?

It returns unidirectional streams. This is actually quite strange; I would naively expect one of the other options as a new developer reading QuicTransport code for the first time. This method should have a qualifier.

Bidirectional streams do a good job of this: `createBidirectionalStream` and `receiveBidirectionalStreams`.
Unidirectional streams should really use: `createUnidirectionalStream` and `receiveUnidirectionalStreams`.

**Comment by yutakahirano** [comment]
Sounds reasonable to me.

This may be a bit off-topic but do we need to have `receiveBidirectionalStreams` and `receiveUnidirectionalStreams` separately? Can we have unified `receiveStreams` whose chunk is either `BidirectionalStream` or `ReceiveStream`?

**Comment by ricea** [comment]
> This may be a bit off-topic but do we need to have receiveBidirectionalStreams and receiveUnidirectionalStreams separately? Can we have unified receiveStreams whose chunk is either BidirectionalStream or ReceiveStream?

Interesting. I like the idea, but I don't want to end up with people using `instanceof` to find out which one they got.

**Comment by kixelated** [comment]
Yeah, I think a unified `receiveStreams` method would require checking the stream type. If you plan on writing to the stream, then you need to check to make sure that it's writable of course. But if you only plan on reading from the stream, then you still need to check if the stream is writable and close it. Otherwise, the stream remains open and counts against flow control limits.

I prefer the separate functions that return concrete types, although I do wish the function names were shorter.

**Comment by vasilvv** [comment]
Another reason to avoid merging them is that in QUIC, backpressure is applied separately to unidirectional and bidirectional streams.  I.e. application could be actively processing incoming unidirectional streams, but not accepting incoming bidirectional streams at all.
